language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - mkdir -p .cargo
  - echo "[build]" > .cargo/config
  - echo "rustflags = [\"-C\", \"target-feature=+popcnt\"]" > .cargo/config
